version: "3"

services:

  service:
    container_name: cache-container
    build: 
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - cache-database
      - redis
    ports:
      - 9090:9090
    env_file:
      - ./src/.env.dev
    volumes:
      - ./src:/app/
  
  cache-database:
    image: postgres:14-alpine
    container_name: cache-database
    ports: 
      - 5433:5432
    environment:
      TZ: "Asia/Tokyo"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cache-database
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d/
      - ./pgdata:/var/lib/postgresql/data

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - "./redis:/data"
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s
